.TH evdaemon "8" "January 2010" "evdaemon 0.1.2" "System administration commands"
.SH NAME
evdaemon \- manual page for evdaemon 0.1.2
.SH SYNOPSIS
.B evdaemon
[\fIOPTION]...\fR
.SH DESCRIPTION
Monitor Linux event devices and modify their behavior.
.SH CONFIGURATION
The evdaemon is started by Upstart process management daemon and
run as a daemon job. All run options are therefore defined in the job
configuration file /etc/init/evdaemon.conf.
.SH OPTIONS
.TP
\fB\-\-daemon\fR
Run evdaemon as a daemon process.
Processing information and error messages are printed only into syslog.
Without this option, logs are also printed into stderr.
.TP
\fB\-h\fR \fB\-\-help\fR
Print text describing all the command line options instead of
preprocessing anything.
.TP
\fB\-V\fR \fB\-\-version\fR
Print out version information and exit.
.SH FILES
.IP /etc/init/evdaemon.conf
.SH AUTHOR
Tuomas Räsänen (tuos) <tuos@codegrove.org>
.SH BUGS
Report evdaemon bugs to <tuos@codegrove.org>
.SH COPYRIGHT
Copyright © 2010 Tuomas Räsänen
.SH LICENSE
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH "SEE ALSO"
.BR modules(5)
.BR init(5)
.BR init(8)
.BR initctl(8)
.BR udevadm(8)
.PP
Home page: <http://codegrove.org/evdaemon/>
